version: "3"
services:
  reverseproxy:
    build:
      context: ./nginx
    image: seifeleslam/udagram-reverseproxy
  backend_user:
    build:
      context: ./udagram-restapi-user
    image: seifeleslam/udagram-restapi-user
  backend_feed:
    build:
      context: ./udagram-restapi-feed  
    image: seifeleslam/udagram-restapi-feed
  frontend:
    build:
      context: ./udagram-frontend
    image: seifeleslam/udagram-frontend
